# Generated by Django 5.2.3 on 2025-08-14 18:24
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleSlot',
            new_name='ScheduleRule',
        ),
    ]