# Generated by Django 5.2.3 on 2025-08-19 16:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20250814_1824'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerule',
            options={'ordering': ['activity_class', 'weekday', 'time']},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='specialities',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schedulerule',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='schedulerule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedulerule',
            name='start',
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='location',
            name='address1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
                migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='location',
                    name='slug',
                    field=models.SlugField(max_length=160, null=True, blank=True),
                )
            ],
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], null=True),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='catalog.coach'),
        ),
        migrations.AlterField(
            model_name='activityclass',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='activity_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rules', to='catalog.activityclass'),
        ),
    ]
