# Generated by Django 5.2.3 on 2025-08-19 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("catalog", "0003_alter_schedulerule_options_remove_coach_bio_and_more")]
    operations = [
        migrations.RunSQL(
            "ALTER TABLE catalog_scheduleslot RENAME TO catalog_schedulerule;",
            "ALTER TABLE catalog_schedulerule RENAME TO catalog_scheduleslot;",
        )
    ]
