# Generated by Django 5.2.3 on 2025-09-22 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_location_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='catalog.activityclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start',),
                'indexes': [models.Index(fields=['activity_class', 'start'], name='catalog_boo_activit_43c7a5_idx'), models.Index(fields=['user', 'start'], name='catalog_boo_user_id_962149_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_class', 'start'), name='booking_unique_user_class_start'), models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='booking_end_after_start')],
            },
        ),
    ]
